version: "3"
services:
  exercise5:
    env_file:
      - .env
    build: .
    image: exercise5
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "${MESSAGE_APP_PORT}:3000"
  mongodb1:
    image: mongo
    volumes:
      - ./data/db1:/data/db
    ports:
      - "${DATABASE1_PORT}:27017"
  mongodb2:
    image: mongo
    volumes:
      - ./data/db2:/data/db
    ports:
      - "${DATABASE2_PORT}:27017"
  doc:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/doc/swagger.yml
    volumes:
      - .messageAppService/doc:/doc
    ports:
      - "${DOC_PORT}:8080"
