version: "3"
services:
  exercise4:
    env_file:
      - .env
    build: .
    image: exercise4
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "${MESSAGE_APP_PORT}:3000"
  mongodb:
    image: mongo
    environment:
      - SWAGGER_JSON=/foo/swagger.json
    volumes:
      - ./data/db:/data/db
    ports:
      - "${DATABASE_PORT}:27017"
  doc:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/doc/swagger.yml
    volumes:
      - .messageAppService/doc:/doc
    ports:
      - "${DOC_PORT}:8080"
